# IF("${PACKAGE_VERSION}" STREQUAL "")
#    MESSAGE(FATAL_ERROR "PACKAGE_VERSION wasn't specified")
# ENDIF("${PACKAGE_VERSION}" STREQUAL "")

IF("${INPUT_FILE}" STREQUAL "")
   MESSAGE(FATAL_ERROR "INPUT_FILE wasn't specified")
ENDIF("${INPUT_FILE}" STREQUAL "")

IF("${OUTPUT_FILE}" STREQUAL "")
   MESSAGE(FATAL_ERROR "OUTPUT_FILE wasn't specified")
ENDIF("${OUTPUT_FILE}" STREQUAL "")

GET_FILENAME_COMPONENT(INPUT_FILE ${INPUT_FILE} ABSOLUTE)
GET_FILENAME_COMPONENT(OUTPUT_FILE ${OUTPUT_FILE} ABSOLUTE)

# Now do some work on CMake variables that are special to this project.
# IF(NOT "${IVP_DATA_DIR}" STREQUAL "")
#    GET_FILENAME_COMPONENT(IVP_DATA_DIR ${IVP_DATA_DIR} ABSOLUTE)
# ENDIF(NOT "${IVP_DATA_DIR}" STREQUAL "")

CONFIGURE_FILE("${INPUT_FILE}" "${OUTPUT_FILE}" @ONLY)
